### ISSUE TITLE
error running moff-gui both linux and windows

### ISSUE THREAD

**Issue by stijn12** [compomics/moff-gui#1]
Hi

I tried to run moff-gui on the example data and it failed with the following error message (in windows).
Any suggestions to solve this issue?

best,

Stijn

Preparing to run moFF...

MoFF will be ran in APEX mode.

Starting moFF run, please note that this is a long process...

Running MoFF in APEX mode.

python C:\Users\me\Downloads\moff-gui-1.1.0\moff-gui-1.1.0\lib\moff\moff.py --tol 10 --output_folder C:\Users\me\Documents --inputraw "E:\moff_sample_data\raw_file\20080313_CPTAC6_07_6A005.RAW" "E:\moff_sample_data\raw_file\20080311_CPTAC6_07_6A005.RAW" --inputtsv "E:\moff_sample_data\20080313_CPTAC6_07_6A005\20080313_CPTAC6_07_6AA05.cpsx.report.tsv" "E:\moff_sample_data\20080311_CPTAC6_07_6A005\20080311_CPTAC6_07_6A005.cpsx.report.tsv" --rt_w 3.0 --rt_p 0.4 --peptide_summary 0

usage: moff.py [-h] --inputtsv NAME [--inputraw RAW_LIST] --tol TOLL

               [--rt_w RT_WINDOW] [--rt_p RT_P_WINDOW]

               [--rt_p_match RT_P_WINDOW_MATCH] [--raw_repo RAW]

               [--output_folder LOC_OUT] [--peptide_summary PEP_MATRIX]

               [--tag_pep_sum_file TAG_PEPSUM]

moff.py: error: unrecognized arguments: E:\moff_sample_data\raw_file\20080311_CPTAC6_07_6A005.RAW E:\moff_sample_data\20080311_CPTAC6_07_6A005\20080311_CPTAC6_07_6A005.cpsx.report.tsv

com.compomics.pladipus.core.model.exception.PladipusProcessingException: An unclear error occurred in a subprocess : 
moff.py: error: unrecognized arguments: E:\moff_sample_data\raw_file\20080311_CPTAC6_07_6A005.RAW E:\moff_sample_data\20080311_CPTAC6_07_6A005\20080311_CPTAC6_07_6A005.cpsx.report.tsv

Finished moFF run

**Comment by Maux82** [comment]
Hi,

I m sorry but the moFF-gui is a bit behind the CLI version and especially the function to parse the cpx data it is use and version the export in PeptideShaker.

I strongly suggest you  to use the command line version meanwhile I will try to update and fix the moFF-GUI version.( I hope in one week maximum)
Actually , moFF-GUI is based on the omd version of moFF that does not use the new Thermo Library.

**Comment by Maux82** [comment]
Hi, 

I have update moFF-GUI with the last version of moFF. Actually, you can use both cpx and tab delimited file as input .  Let me know if you find some problem or error
